# -*- coding: utf-8 -*-
"""desafio 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r_h6bjy2LbkQj7m4v_GoiOr-Maoctw6e
"""

import pandas as pd

df_stocks = pd.read_csv('dados_acoes.csv')
df_market = pd.read_csv('dados_mercado.csv')

stocks_prices = df_stocks[['Date', 'Close']]
market_prices = df_market[['Date', 'Close']]

stocks_prices.set_index('Date', inplace=True)
market_prices.set_index('Date', inplace=True)

returns_stocks = stocks_prices.pct_change()
returns_market = market_prices.pct_change()

cov = returns_stocks.cov(returns_market)

var_market = returns_market.var()

beta = cov / var_market

print(beta)