# -*- coding: utf-8 -*-
"""desafio 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g86kuAyftGjgYn9q6i_xZwst0rO1gftI

Crie um programa em Python que utilize o modelo de precificação de opções BlackScholes para avaliar o preço de uma opção de compra ou venda. O programa deve ser
capaz de receber informações sobre o preço atual do ativo subjacente, a taxa livre de
risco, a volatilidade do ativo e o tempo restante até o vencimento da opção.
"""

import math
from scipy.stats import norm

def black_scholes(s, k, t, r, v, tipo_opcao):
  
    d1 = (math.log(s / k) + (r + 0.5 * v * v) * t) / (v * math.sqrt(t))
    d2 = d1 - v * math.sqrt(t)
    if tipo_opcao == "call":
        return s * norm.cdf(d1) - k * math.exp(-r * t) * norm.cdf(d2)
    elif tipo_opcao == "put":
        return k * math.exp(-r * t) * norm.cdf(-d2) - s * norm.cdf(-d1)
    else:
        raise ValueError("Opção inválida. Escolha 'call' ou 'put'.")

s = float(input("Preço atual do ativo subjacente: "))
k = float(input("Preço de exercício da opção: "))
t = float(input("Tempo restante até o vencimento da opção (em anos): "))
r = float(input("Taxa livre de risco: "))
v = float(input("Volatilidade do ativo: "))
tipo_opcao = input("Tipo de opção (call/put): ")

preco_opcao = black_scholes(s, k, t, r, v, tipo_opcao)

print("O preço da opção é: ", preco_opcao)